<?php


namespace App\Services;


use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\File;

class UploadFile
{
    public function uploadFile($fileName, $path)
    {

        if (!is_null($fileName) && $fileName != "")
        {
            $file           = new File($fileName);
            $NewfileName    = $this->generateUniqueFileName() .'.'. $file->guessExtension();

            try {
                $file->move($path, $NewfileName);
                return $NewfileName;

            } catch (FileException $e)
            {
                die($e->getMessage());
            }
        }

    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}